In [13]:
# Kết nối Google Drive với Colab
from google.colab import drive
drive.mount('/content/drive')

# Nhập thư viện pandas để xử lý dữ liệu
import pandas as pd

# Đường dẫn tệp France.xlsx
file_path = '/content/drive/MyDrive/Cleaned data/Cleaned_Vietnam_volume.xlsx'

# Đọc danh sách các sheet trong tệp
excel_file = pd.ExcelFile(file_path)
sheets = excel_file.sheet_names  # Danh sách tên sheet
print(f"Danh sách các sheets: {sheets}")

# Đọc dữ liệu từ từng sheet
sheet1 = pd.read_excel(file_path, sheet_name='Sheet1')
sheet2 = pd.read_excel(file_path, sheet_name='Sheet2')

# Hiển thị vài dòng đầu của từng sheet

print("\nSheet: Sheet1")
print(sheet1.head())

print("\nSheet: Sheet2")
print(sheet2.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Danh sách các sheets: ['Sheet1', 'Sheet2']

Sheet: Sheet1
                             Name Symbol      RIC  Start Date  Hist.  \
0  JST.CMLBK.FOR FRT. OF VIET NAM    VCB   VCB.HM   6/30/2009   2009
1                  VIX SECURITIES    VIX   VIX.HM  12/29/2009   2009
2                  120 MECHANICAL    CK8  CK8.HNO    4/7/2023   2023
3               1369 CONSTRUCTION    C69   C69.HN   4/21/2017   2017
4          22 JOINT STOCK COMPANY    C22  C22.HNO   5/24/2018   2018

   Category     Exchange   Market         Currency  \
0  Equities  Ho Chi Minh  Vietnam  Vietnamese Dong
1  Equities  Ho Chi Minh  Vietnam  Vietnamese Dong
2  Equities    Hanoi OTC  Vietnam  Vietnamese Dong
3  Equities        Hanoi  Vietnam  Vietnamese Dong
4  Equities    Hanoi OTC  Vietnam  Vietnamese Dong

                       Sector  \
0                       Banks
1                           -
2                Unclassified
3  Construction and Materials
4              Food Producers

                                           Full Name Activity
0  Joint Stock Commercial Bank for Foreign Trade ...   Active
1                                     VIX Securities   Active
2                                     120 Mechanical   Active
3                                  1369 Construction   Active
4                             22 Joint Stock Company   Active

Sheet: Sheet2
                                                Name     Code  \
0  JST.CMLBK.FOR FRT. OF VIET NAM - TURNOVER BY V...  VCB(VO)
1                VIX SECURITIES - TURNOVER BY VOLUME  VIX(VO)
2                120 MECHANICAL - TURNOVER BY VOLUME  CK8(VO)
3             1369 CONSTRUCTION - TURNOVER BY VOLUME  C69(VO)
4        22 JOINT STOCK COMPANY - TURNOVER BY VOLUME  C22(VO)

  2019-03-01 00:00:00  2019-03-04 00:00:00  2019-03-05 00:00:00  \
0              1075.3               2030.7               2376.2
1               124.5                246.5                168.4
2                 NaN                  NaN                  NaN
3                 0.1                 25.3                 35.6
4                 NaN                  NaN                  NaN

   2019-03-06 00:00:00  2019-03-07 00:00:00  2019-03-08 00:00:00  \
0               1630.4               2859.5               1503.1
1                276.5                152.8                 55.5
2                  NaN                  NaN                  NaN
3                 53.0                 63.2                244.6
4                  NaN                  NaN                  NaN

   2019-03-11 00:00:00  2019-03-12 00:00:00  ...  2025-02-18 00:00:00  \
0               1538.1               3307.0  ...               1065.5
1                116.0                327.3  ...              42349.2
2                  NaN                  NaN  ...                  NaN
3                 19.9                 91.8  ...                621.4
4                  NaN                  NaN  ...                  NaN

   2025-02-19 00:00:00  2025-02-20 00:00:00  2025-02-21 00:00:00  \
0               1509.5               1636.6               2513.4
1              49089.7              49075.5              29387.6
2                  NaN                  NaN                  NaN
3                522.9                727.0                637.5
4                  NaN                  NaN                  NaN

   2025-02-24 00:00:00  2025-02-25 00:00:00  2025-02-26 00:00:00  \
0               1956.0               1926.6                769.2
1              42255.3              51596.3              36947.4
2                  NaN                  NaN                  NaN
3                360.6                367.0                360.9
4                  NaN                  NaN                  1.5

   2025-02-27 00:00:00  2025-02-28 00:00:00  2025-03-03 00:00:00
0               5028.8               2070.8               1251.0
1              39566.7              35634.8              65459.4
2                  NaN                  NaN                  NaN
3                357.1                346.1                447.8
4                  0.6                  0.1                  0.2

[5 rows x 1569 columns]

In [14]:
# Lọc các dòng có lỗi (#ERROR hoặc $$ER)
error_rows = sheet2[sheet2.apply(lambda x: x.astype(str).str.contains(r'#ERROR|\$\$ER', regex=True, na=False)).any(axis=1)]

# Hiển thị số dòng lỗi
print(f"Số dòng bị lỗi: {len(error_rows)}")

# Hiển thị các dòng lỗi
display(error_rows)

Số dòng bị lỗi: 152

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
258,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1136,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1220,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1457,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,#ERROR,NaN,"$$ER: E100,INVALID CODE OR EXPRESSION ENTERED",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1930,#ERROR,NaN,"$$ER: E100,INVALID CODE OR EXPRESSION ENTERED",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1931,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1932,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1933,#ERROR,NaN,"$$ER: 0904,NO DATA AVAILABLE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
sheet2 = sheet2[~sheet2.apply(lambda x: x.astype(str).str.contains('#ERROR|\$\$ER', regex=True, na=False)).any(axis=1)]
sheet2

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
0,JST.CMLBK.FOR FRT. OF VIET NAM - TURNOVER BY V...,VCB(VO),1075.3,2030.7,2376.2,1630.4,2859.5,1503.1,1538.1,3307.0,...,1065.5,1509.5,1636.6,2513.4,1956.0,1926.6,769.2,5028.8,2070.8,1251.0
1,VIX SECURITIES - TURNOVER BY VOLUME,VIX(VO),124.5,246.5,168.4,276.5,152.8,55.5,116.0,327.3,...,42349.2,49089.7,49075.5,29387.6,42255.3,51596.3,36947.4,39566.7,35634.8,65459.4
2,120 MECHANICAL - TURNOVER BY VOLUME,CK8(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1369 CONSTRUCTION - TURNOVER BY VOLUME,C69(VO),0.1,25.3,35.6,53.0,63.2,244.6,19.9,91.8,...,621.4,522.9,727.0,637.5,360.6,367.0,360.9,357.1,346.1,447.8
4,22 JOINT STOCK COMPANY - TURNOVER BY VOLUME,C22(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.6,0.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1905,VISACO MINERAL AND INV. DEAD - DELIST.19/09/22...,VMI(VO),NaN,NaN,NaN,NaN,67.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,VTM.TV.CAB.JSC. DEAD - DELIST.31/12/24 - TURNO...,CAB(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,X18 CEMENT DEAD - DELIST.17/07/20 - TURNOVER B...,X18(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,YENLAO RAILWAY DEAD - DELIST.13/08/21 - TURNOV...,2563UZ(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,ORIENT SECURITIE DEAD - DELIST.10/04/19 - TURN...,69755L(VO),22.4,NaN,2.0,NaN,1.0,11.1,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# Lọc các dòng có chứa từ "DEAD" trong cột 'Name'
dead_rows = sheet2[sheet2['Name'].str.contains('DEAD', na=False, case=False)]

# Hiển thị số dòng và các dòng bị lỗi
print(f"Số dòng chứa 'DEAD': {len(dead_rows)}")
# Hiển thị các dòng lỗi
display(dead_rows)

Số dòng chứa 'DEAD': 127

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
961,QUANG NAM MINERA DEAD - DELIST.04/03/25 - TURN...,MIC(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.8,49.7,106.6,38.3,113.6,32.6,154.6,15.5,55.1,NaN
1598,145 ONE MEB.LLC. DEAD - DELIST.04/04/22 - TURN...,TS5(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,28 HUNG PHU DEAD - DELIST.04/06/21 - TURNOVER ...,9237X7(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,28 QUANG NGAI DEAD - DELIST.02/07/21 - TURNOVE...,9448DL(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1601,319 STHN.INCON.JSC DEAD - DELIST.28/10/20 - TU...,BM9(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1905,VISACO MINERAL AND INV. DEAD - DELIST.19/09/22...,VMI(VO),NaN,NaN,NaN,NaN,67.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,VTM.TV.CAB.JSC. DEAD - DELIST.31/12/24 - TURNO...,CAB(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,X18 CEMENT DEAD - DELIST.17/07/20 - TURNOVER B...,X18(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,YENLAO RAILWAY DEAD - DELIST.13/08/21 - TURNOV...,2563UZ(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,ORIENT SECURITIE DEAD - DELIST.10/04/19 - TURN...,69755L(VO),22.4,NaN,2.0,NaN,1.0,11.1,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Xóa phần từ "DEAD" trở đi trong cột 'Name'
sheet2['Name'] = sheet2['Name'].str.split(' DEAD').str[0]
sheet2

<ipython-input-18-9184616ee2c6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sheet2['Name'] = sheet2['Name'].str.split(' DEAD').str[0]

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
0,JST.CMLBK.FOR FRT. OF VIET NAM - TURNOVER BY V...,VCB(VO),1075.3,2030.7,2376.2,1630.4,2859.5,1503.1,1538.1,3307.0,...,1065.5,1509.5,1636.6,2513.4,1956.0,1926.6,769.2,5028.8,2070.8,1251.0
1,VIX SECURITIES - TURNOVER BY VOLUME,VIX(VO),124.5,246.5,168.4,276.5,152.8,55.5,116.0,327.3,...,42349.2,49089.7,49075.5,29387.6,42255.3,51596.3,36947.4,39566.7,35634.8,65459.4
2,120 MECHANICAL - TURNOVER BY VOLUME,CK8(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1369 CONSTRUCTION - TURNOVER BY VOLUME,C69(VO),0.1,25.3,35.6,53.0,63.2,244.6,19.9,91.8,...,621.4,522.9,727.0,637.5,360.6,367.0,360.9,357.1,346.1,447.8
4,22 JOINT STOCK COMPANY - TURNOVER BY VOLUME,C22(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.6,0.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1905,VISACO MINERAL AND INV.,VMI(VO),NaN,NaN,NaN,NaN,67.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,VTM.TV.CAB.JSC.,CAB(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,X18 CEMENT,X18(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,YENLAO RAILWAY,2563UZ(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,ORIENT SECURITIE,69755L(VO),22.4,NaN,2.0,NaN,1.0,11.1,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Xóa phần sau dấu gạch nối (bao gồm dấu gạch nối) trong cột 'Name'
sheet2['Name'] = sheet2['Name'].str.split(' -').str[0]

sheet2

<ipython-input-19-552186409840>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sheet2['Name'] = sheet2['Name'].str.split(' -').str[0]

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
0,JST.CMLBK.FOR FRT. OF VIET NAM,VCB(VO),1075.3,2030.7,2376.2,1630.4,2859.5,1503.1,1538.1,3307.0,...,1065.5,1509.5,1636.6,2513.4,1956.0,1926.6,769.2,5028.8,2070.8,1251.0
1,VIX SECURITIES,VIX(VO),124.5,246.5,168.4,276.5,152.8,55.5,116.0,327.3,...,42349.2,49089.7,49075.5,29387.6,42255.3,51596.3,36947.4,39566.7,35634.8,65459.4
2,120 MECHANICAL,CK8(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1369 CONSTRUCTION,C69(VO),0.1,25.3,35.6,53.0,63.2,244.6,19.9,91.8,...,621.4,522.9,727.0,637.5,360.6,367.0,360.9,357.1,346.1,447.8
4,22 JOINT STOCK COMPANY,C22(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.6,0.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1905,VISACO MINERAL AND INV.,VMI(VO),NaN,NaN,NaN,NaN,67.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,VTM.TV.CAB.JSC.,CAB(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,X18 CEMENT,X18(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,YENLAO RAILWAY,2563UZ(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,ORIENT SECURITIE,69755L(VO),22.4,NaN,2.0,NaN,1.0,11.1,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Danh sách cột cần lấy từ sheet1 qua sheet2
columns_to_merge =  ['Name', 'RIC', 'Start Date', 'Exchange', 'Sector', 'Activity']
sheet2 = pd.merge(sheet2, sheet1[columns_to_merge], on='Name', how='left', suffixes=('_sheet2', '_sheet1'))

sheet2

,Name,Code,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,2019-03-06 00:00:00,2019-03-07 00:00:00,2019-03-08 00:00:00,2019-03-11 00:00:00,2019-03-12 00:00:00,...,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00,RIC,Start Date,Exchange,Sector,Activity
0,JST.CMLBK.FOR FRT. OF VIET NAM,VCB(VO),1075.3,2030.7,2376.2,1630.4,2859.5,1503.1,1538.1,3307.0,...,1926.6,769.2,5028.8,2070.8,1251.0,VCB.HM,6/30/2009,Ho Chi Minh,Banks,Active
1,VIX SECURITIES,VIX(VO),124.5,246.5,168.4,276.5,152.8,55.5,116.0,327.3,...,51596.3,36947.4,39566.7,35634.8,65459.4,VIX.HM,12/29/2009,Ho Chi Minh,-,Active
2,120 MECHANICAL,CK8(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CK8.HNO,4/7/2023,Hanoi OTC,Unclassified,Active
3,1369 CONSTRUCTION,C69(VO),0.1,25.3,35.6,53.0,63.2,244.6,19.9,91.8,...,367.0,360.9,357.1,346.1,447.8,C69.HN,4/21/2017,Hanoi,Construction and Materials,Active
4,22 JOINT STOCK COMPANY,C22(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.5,0.6,0.1,0.2,C22.HNO,5/24/2018,Hanoi OTC,Food Producers,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,VISACO MINERAL AND INV.,VMI(VO),NaN,NaN,NaN,NaN,67.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,VMI.HNO^I22,10/9/2014,Hanoi OTC,Construction and Materials,Dead
1803,VTM.TV.CAB.JSC.,CAB(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CAB.HNO^L24,4/18/2022,Hanoi OTC,Unclassified,Dead
1804,X18 CEMENT,X18(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,X18.HNO^G20,1/19/2017,Hanoi OTC,Unclassified,Dead
1805,YENLAO RAILWAY,2563UZ(VO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,YRC.HNO^H21,9/9/2016,Hanoi OTC,Industrial Transportation,Dead
1806,ORIENT SECURITIE,69755L(VO),22.4,NaN,2.0,NaN,1.0,11.1,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,-,7/12/2010,Hanoi,-,Dead

In [23]:
# Lấy danh sách cột hiện tại
cols = sheet2.columns.tolist()

# Xác định các cột cần sắp xếp lại
columns_to_move = ['RIC', 'Start Date', 'Exchange', 'Sector', 'Activity']

# Đảm bảo các cột cần di chuyển có trong DataFrame (tránh lỗi nếu thiếu cột nào)
columns_to_move = [col for col in columns_to_move if col in cols]

# Loại bỏ các cột này khỏi danh sách ban đầu để tránh trùng lặp
remaining_cols = [col for col in cols if col not in ['Name', 'Code'] + columns_to_move]

# Xác định thứ tự cột mới
new_order = ['Name', 'Code'] + columns_to_move + remaining_cols

# Sắp xếp lại DataFrame theo thứ tự mới
sheet2 = sheet2[new_order]

# Hiển thị DataFrame sau khi sắp xếp
display(sheet2)

,Name,Code,RIC,Start Date,Exchange,Sector,Activity,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
0,JST.CMLBK.FOR FRT. OF VIET NAM,VCB,VCB.HM,6/30/2009,Ho Chi Minh,Banks,Active,1075.3,2030.7,2376.2,...,1065.5,1509.5,1636.6,2513.4,1956.0,1926.6,769.2,5028.8,2070.8,1251.0
1,VIX SECURITIES,VIX,VIX.HM,12/29/2009,Ho Chi Minh,-,Active,124.5,246.5,168.4,...,42349.2,49089.7,49075.5,29387.6,42255.3,51596.3,36947.4,39566.7,35634.8,65459.4
2,120 MECHANICAL,CK8,CK8.HNO,4/7/2023,Hanoi OTC,Unclassified,Active,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1369 CONSTRUCTION,C69,C69.HN,4/21/2017,Hanoi,Construction and Materials,Active,0.1,25.3,35.6,...,621.4,522.9,727.0,637.5,360.6,367.0,360.9,357.1,346.1,447.8
4,22 JOINT STOCK COMPANY,C22,C22.HNO,5/24/2018,Hanoi OTC,Food Producers,Active,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.6,0.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,VISACO MINERAL AND INV.,VMI,VMI.HNO^I22,10/9/2014,Hanoi OTC,Construction and Materials,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803,VTM.TV.CAB.JSC.,CAB,CAB.HNO^L24,4/18/2022,Hanoi OTC,Unclassified,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1804,X18 CEMENT,X18,X18.HNO^G20,1/19/2017,Hanoi OTC,Unclassified,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1805,YENLAO RAILWAY,2563UZ,YRC.HNO^H21,9/9/2016,Hanoi OTC,Industrial Transportation,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1806,ORIENT SECURITIE,69755L,-,7/12/2010,Hanoi,-,Dead,22.4,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
sheet2['Code'] = sheet2['Code'].str.replace(r'\(VO\)', '', regex=True)
sheet2

,Name,Code,RIC,Start Date,Exchange,Sector,Activity,2019-03-01 00:00:00,2019-03-04 00:00:00,2019-03-05 00:00:00,...,2025-02-18 00:00:00,2025-02-19 00:00:00,2025-02-20 00:00:00,2025-02-21 00:00:00,2025-02-24 00:00:00,2025-02-25 00:00:00,2025-02-26 00:00:00,2025-02-27 00:00:00,2025-02-28 00:00:00,2025-03-03 00:00:00
0,JST.CMLBK.FOR FRT. OF VIET NAM,VCB,VCB.HM,6/30/2009,Ho Chi Minh,Banks,Active,1075.3,2030.7,2376.2,...,1065.5,1509.5,1636.6,2513.4,1956.0,1926.6,769.2,5028.8,2070.8,1251.0
1,VIX SECURITIES,VIX,VIX.HM,12/29/2009,Ho Chi Minh,-,Active,124.5,246.5,168.4,...,42349.2,49089.7,49075.5,29387.6,42255.3,51596.3,36947.4,39566.7,35634.8,65459.4
2,120 MECHANICAL,CK8,CK8.HNO,4/7/2023,Hanoi OTC,Unclassified,Active,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1369 CONSTRUCTION,C69,C69.HN,4/21/2017,Hanoi,Construction and Materials,Active,0.1,25.3,35.6,...,621.4,522.9,727.0,637.5,360.6,367.0,360.9,357.1,346.1,447.8
4,22 JOINT STOCK COMPANY,C22,C22.HNO,5/24/2018,Hanoi OTC,Food Producers,Active,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.6,0.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,VISACO MINERAL AND INV.,VMI,VMI.HNO^I22,10/9/2014,Hanoi OTC,Construction and Materials,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803,VTM.TV.CAB.JSC.,CAB,CAB.HNO^L24,4/18/2022,Hanoi OTC,Unclassified,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1804,X18 CEMENT,X18,X18.HNO^G20,1/19/2017,Hanoi OTC,Unclassified,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1805,YENLAO RAILWAY,2563UZ,YRC.HNO^H21,9/9/2016,Hanoi OTC,Industrial Transportation,Dead,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1806,ORIENT SECURITIE,69755L,-,7/12/2010,Hanoi,-,Dead,22.4,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
import pandas as pd

# Đường dẫn để lưu file
output_file_path = "/content/drive/MyDrive/Cleaned data/Processed_Vietnam_volume_2.xlsx"

# Xuất sheet2 ra file Excel
sheet2.to_excel(output_file_path, sheet_name="Processed_Sheet2", index=False)

print(f"Dữ liệu đã được lưu vào: {output_file_path}")

Dữ liệu đã được lưu vào: /content/drive/MyDrive/Cleaned data/Processed_Vietnam_volume_2.xlsx